defaults:
    - base_mixture
    - agent: sac

# this needs to be specified manually
experiment: PEBBLE_mixture_diagnostics

# hydra configuration
hydra:
    run:
        dir: ./exp_pebble_mixture_diagnostics/${env}/max_feedback${max_feedback}_feed_type${feed_type}_n${reward_batch}_l${segment}_g${teacher_gamma}_b${teacher_betas}_m${teacher_eps_mistake}_s${teacher_eps_skip}_e${teacher_eps_equal}/seed${seed}/
